***Car Price Prediction***

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
car = pd.read_csv("/content/drive/MyDrive/datasets/car.csv")
car

car_ID  symboling                   CarName fueltype aspiration  \
0         1          3        alfa-romero giulia      gas        std   
1         2          3       alfa-romero stelvio      gas        std   
2         3          1  alfa-romero Quadrifoglio      gas        std   
3         4          2               audi 100 ls      gas        std   
4         5          2                audi 100ls      gas        std   
..      ...        ...                       ...      ...        ...   
200     201         -1           volvo 145e (sw)      gas        std   
201     202         -1               volvo 144ea      gas      turbo   
202     203         -1               volvo 244dl      gas        std   
203     204         -1                 volvo 246   diesel      turbo   
204     205         -1               volvo 264gl      gas      turbo   

    doornumber      carbody drivewheel enginelocation  wheelbase  ...  \
0          two  convertible        rwd          front       88.6  ...   
1          two  convertible        rwd          front       88.6  ...   
2          two    hatchback        rwd          front       94.5  ...   
3         four        sedan        fwd          front       99.8  ...   
4         four        sedan        4wd          front       99.4  ...   
..         ...          ...        ...            ...        ...  ...   
200       four        sedan        rwd          front      109.1  ...   
201       four        sedan        rwd          front      109.1  ...   
202       four        sedan        rwd          front      109.1  ...   
203       four        sedan        rwd          front      109.1  ...   
204       four        sedan        rwd          front      109.1  ...   

     enginesize  fuelsystem  boreratio  stroke compressionratio horsepower  \
0           130        mpfi       3.47    2.68              9.0        111   
1           130        mpfi       3.47    2.68              9.0        111   
2           152        mpfi       2.68    3.47              9.0        154   
3           109        mpfi       3.19    3.40             10.0        102   
4           136        mpfi       3.19    3.40              8.0        115   
..          ...         ...        ...     ...              ...        ...   
200         141        mpfi       3.78    3.15              9.5        114   
201         141        mpfi       3.78    3.15              8.7        160   
202         173        mpfi       3.58    2.87              8.8        134   
203         145         idi       3.01    3.40             23.0        106   
204         141        mpfi       3.78    3.15              9.5        114   

     peakrpm citympg  highwaympg    price  
0       5000      21          27  13495.0  
1       5000      21          27  16500.0  
2       5000      19          26  16500.0  
3       5500      24          30  13950.0  
4       5500      18          22  17450.0  
..       ...     ...         ...      ...  
200     5400      23          28  16845.0  
201     5300      19          25  19045.0  
202     5500      18          23  21485.0  
203     4800      26          27  22470.0  
204     5400      19          25  22625.0  

[205 rows x 26 columns]

In [ ]:
car.head()

car_ID  symboling                   CarName fueltype aspiration doornumber  \
0       1          3        alfa-romero giulia      gas        std        two   
1       2          3       alfa-romero stelvio      gas        std        two   
2       3          1  alfa-romero Quadrifoglio      gas        std        two   
3       4          2               audi 100 ls      gas        std       four   
4       5          2                audi 100ls      gas        std       four   

       carbody drivewheel enginelocation  wheelbase  ...  enginesize  \
0  convertible        rwd          front       88.6  ...         130   
1  convertible        rwd          front       88.6  ...         130   
2    hatchback        rwd          front       94.5  ...         152   
3        sedan        fwd          front       99.8  ...         109   
4        sedan        4wd          front       99.4  ...         136   

   fuelsystem  boreratio  stroke compressionratio horsepower  peakrpm citympg  \
0        mpfi       3.47    2.68              9.0        111     5000      21   
1        mpfi       3.47    2.68              9.0        111     5000      21   
2        mpfi       2.68    3.47              9.0        154     5000      19   
3        mpfi       3.19    3.40             10.0        102     5500      24   
4        mpfi       3.19    3.40              8.0        115     5500      18   

   highwaympg    price  
0          27  13495.0  
1          27  16500.0  
2          26  16500.0  
3          30  13950.0  
4          22  17450.0  

[5 rows x 26 columns]

In [ ]:
car.tail()

car_ID  symboling          CarName fueltype aspiration doornumber  \
200     201         -1  volvo 145e (sw)      gas        std       four   
201     202         -1      volvo 144ea      gas      turbo       four   
202     203         -1      volvo 244dl      gas        std       four   
203     204         -1        volvo 246   diesel      turbo       four   
204     205         -1      volvo 264gl      gas      turbo       four   

    carbody drivewheel enginelocation  wheelbase  ...  enginesize  fuelsystem  \
200   sedan        rwd          front      109.1  ...         141        mpfi   
201   sedan        rwd          front      109.1  ...         141        mpfi   
202   sedan        rwd          front      109.1  ...         173        mpfi   
203   sedan        rwd          front      109.1  ...         145         idi   
204   sedan        rwd          front      109.1  ...         141        mpfi   

     boreratio  stroke compressionratio horsepower  peakrpm citympg  \
200       3.78    3.15              9.5        114     5400      23   
201       3.78    3.15              8.7        160     5300      19   
202       3.58    2.87              8.8        134     5500      18   
203       3.01    3.40             23.0        106     4800      26   
204       3.78    3.15              9.5        114     5400      19   

     highwaympg    price  
200          28  16845.0  
201          25  19045.0  
202          23  21485.0  
203          27  22470.0  
204          25  22625.0  

[5 rows x 26 columns]

In [ ]:
car.shape

(205, 26)

In [ ]:
car.describe()

car_ID   symboling   wheelbase   carlength    carwidth   carheight  \
count  205.000000  205.000000  205.000000  205.000000  205.000000  205.000000   
mean   103.000000    0.834146   98.756585  174.049268   65.907805   53.724878   
std     59.322565    1.245307    6.021776   12.337289    2.145204    2.443522   
min      1.000000   -2.000000   86.600000  141.100000   60.300000   47.800000   
25%     52.000000    0.000000   94.500000  166.300000   64.100000   52.000000   
50%    103.000000    1.000000   97.000000  173.200000   65.500000   54.100000   
75%    154.000000    2.000000  102.400000  183.100000   66.900000   55.500000   
max    205.000000    3.000000  120.900000  208.100000   72.300000   59.800000   

        curbweight  enginesize   boreratio      stroke  compressionratio  \
count   205.000000  205.000000  205.000000  205.000000        205.000000   
mean   2555.565854  126.907317    3.329756    3.255415         10.142537   
std     520.680204   41.642693    0.270844    0.313597          3.972040   
min    1488.000000   61.000000    2.540000    2.070000          7.000000   
25%    2145.000000   97.000000    3.150000    3.110000          8.600000   
50%    2414.000000  120.000000    3.310000    3.290000          9.000000   
75%    2935.000000  141.000000    3.580000    3.410000          9.400000   
max    4066.000000  326.000000    3.940000    4.170000         23.000000   

       horsepower      peakrpm     citympg  highwaympg         price  
count  205.000000   205.000000  205.000000  205.000000    205.000000  
mean   104.117073  5125.121951   25.219512   30.751220  13276.710571  
std     39.544167   476.985643    6.542142    6.886443   7988.852332  
min     48.000000  4150.000000   13.000000   16.000000   5118.000000  
25%     70.000000  4800.000000   19.000000   25.000000   7788.000000  
50%     95.000000  5200.000000   24.000000   30.000000  10295.000000  
75%    116.000000  5500.000000   30.000000   34.000000  16503.000000  
max    288.000000  6600.000000   49.000000   54.000000  45400.000000

In [ ]:
car.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   car_ID            205 non-null    int64  
 1   symboling         205 non-null    int64  
 2   CarName           205 non-null    object 
 3   fueltype          205 non-null    object 
 4   aspiration        205 non-null    object 
 5   doornumber        205 non-null    object 
 6   carbody           205 non-null    object 
 7   drivewheel        205 non-null    object 
 8   enginelocation    205 non-null    object 
 9   wheelbase         205 non-null    float64
 10  carlength         205 non-null    float64
 11  carwidth          205 non-null    float64
 12  carheight         205 non-null    float64
 13  curbweight        205 non-null    int64  
 14  enginetype        205 non-null    object 
 15  cylindernumber    205 non-null    object 
 16  enginesize        205 non-null    int64  
 1

In [ ]:
car.isnull().sum()

car_ID              0
symboling           0
CarName             0
fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [ ]:
car['fueltype'].unique()

array(['gas', 'diesel'], dtype=object)

In [ ]:
car["doornumber"].unique()

array(['two', 'four'], dtype=object)

In [ ]:
car['enginetype'].unique()

array(['dohc', 'ohcv', 'ohc', 'l', 'rotor', 'ohcf', 'dohcv'], dtype=object)

In [ ]:
car['fuelsystem'].unique()

array(['mpfi', '2bbl', 'mfi', '1bbl', 'spfi', '4bbl', 'idi', 'spdi'],
      dtype=object)

In [ ]:
car=car.drop(columns=["car_ID","symboling","aspiration","carbody","drivewheel","enginelocation","wheelbase","carlength","carwidth","carheight","curbweight","cylindernumber","enginesize","boreratio","stroke","compressionratio","peakrpm","citympg","highwaympg" ],axis=1)




In [ ]:
car.shape

(205, 7)

In [ ]:
car

CarName fueltype doornumber enginetype fuelsystem  \
0          alfa-romero giulia      gas        two       dohc       mpfi   
1         alfa-romero stelvio      gas        two       dohc       mpfi   
2    alfa-romero Quadrifoglio      gas        two       ohcv       mpfi   
3                 audi 100 ls      gas       four        ohc       mpfi   
4                  audi 100ls      gas       four        ohc       mpfi   
..                        ...      ...        ...        ...        ...   
200           volvo 145e (sw)      gas       four        ohc       mpfi   
201               volvo 144ea      gas       four        ohc       mpfi   
202               volvo 244dl      gas       four       ohcv       mpfi   
203                 volvo 246   diesel       four        ohc        idi   
204               volvo 264gl      gas       four        ohc       mpfi   

     horsepower    price  
0           111  13495.0  
1           111  16500.0  
2           154  16500.0  
3           102  13950.0  
4           115  17450.0  
..          ...      ...  
200         114  16845.0  
201         160  19045.0  
202         134  21485.0  
203         106  22470.0  
204         114  22625.0  

[205 rows x 7 columns]

In [ ]:
car.head(3)

CarName fueltype doornumber enginetype fuelsystem  \
0        alfa-romero giulia      gas        two       dohc       mpfi   
1       alfa-romero stelvio      gas        two       dohc       mpfi   
2  alfa-romero Quadrifoglio      gas        two       ohcv       mpfi   

   horsepower    price  
0         111  13495.0  
1         111  16500.0  
2         154  16500.0

In [ ]:
from sklearn.preprocessing import LabelEncoder


In [ ]:
lencode=LabelEncoder()
car['fuelsystem']=lencode.fit_transform(car[['fuelsystem']])
car['CarName']=lencode.fit_transform(car[['CarName']])
car['horsepower']=lencode.fit_transform(car[['horsepower']])
car['fueltype']=lencode.fit_transform(car[['fueltype']])
car['doornumber']=lencode.fit_transform(car[['doornumber']])
car['price']=lencode.fit_transform(car[['price']])
car['enginetype']=lencode.fit_transform(car[['enginetype']])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,

In [ ]:
from sklearn.preprocessing import MinMaxScaler
le=MinMaxScaler()
car['fuelsystem']=le.fit_transform(car[['fuelsystem']])
car['CarName']=le.fit_transform(car[['CarName']])
car['horsepower']=le.fit_transform(car[['horsepower']])

car['fuelsystem']=le.fit_transform(car[['fuelsystem']])
car['fueltype']=le.fit_transform(car[['fueltype']])
car['doornumber']=le.fit_transform(car[['doornumber']])
car['enginetype']=le.fit_transform(car[['enginetype']])
car['price']=le.fit_transform(car[['price']])


In [ ]:
car['fuelsystem'].unique()

array([0.71428571, 0.14285714, 0.57142857, 0.        , 1.        ,
       0.28571429, 0.42857143, 0.85714286])

In [ ]:
car['enginetype'].unique()

array([0.        , 0.83333333, 0.5       , 0.33333333, 1.        ,
       0.66666667, 0.16666667])

In [ ]:
car['fueltype'].unique()

array([1., 0.])

In [ ]:
car['doornumber'].unique()

array([1., 0.])

In [ ]:
car

CarName  fueltype  doornumber  enginetype  fuelsystem  horsepower  \
0    0.013699       1.0         1.0    0.000000    0.714286    0.517241   
1    0.020548       1.0         1.0    0.000000    0.714286    0.517241   
2    0.006849       1.0         1.0    0.833333    0.714286    0.775862   
3    0.027397       1.0         0.0    0.500000    0.714286    0.465517   
4    0.034247       1.0         0.0    0.500000    0.714286    0.568966   
..        ...       ...         ...         ...         ...         ...   
200  0.952055       1.0         0.0    0.500000    0.714286    0.551724   
201  0.945205       1.0         0.0    0.500000    0.714286    0.827586   
202  0.958904       1.0         0.0    0.833333    0.714286    0.655172   
203  0.972603       0.0         0.0    0.500000    0.428571    0.482759   
204  0.979452       1.0         0.0    0.500000    0.714286    0.551724   

        price  
0    0.627660  
1    0.728723  
2    0.728723  
3    0.654255  
4    0.787234  
..        ...  
200  0.760638  
201  0.856383  
202  0.877660  
203  0.888298  
204  0.893617  

[205 rows x 7 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
car

CarName  fueltype  doornumber  enginetype  fuelsystem  horsepower  \
0    0.013699       1.0         1.0    0.000000    0.714286    0.517241   
1    0.020548       1.0         1.0    0.000000    0.714286    0.517241   
2    0.006849       1.0         1.0    0.833333    0.714286    0.775862   
3    0.027397       1.0         0.0    0.500000    0.714286    0.465517   
4    0.034247       1.0         0.0    0.500000    0.714286    0.568966   
..        ...       ...         ...         ...         ...         ...   
200  0.952055       1.0         0.0    0.500000    0.714286    0.551724   
201  0.945205       1.0         0.0    0.500000    0.714286    0.827586   
202  0.958904       1.0         0.0    0.833333    0.714286    0.655172   
203  0.972603       0.0         0.0    0.500000    0.428571    0.482759   
204  0.979452       1.0         0.0    0.500000    0.714286    0.551724   

        price  
0    0.627660  
1    0.728723  
2    0.728723  
3    0.654255  
4    0.787234  
..        ...  
200  0.760638  
201  0.856383  
202  0.877660  
203  0.888298  
204  0.893617  

[205 rows x 7 columns]

In [ ]:
x=car.iloc[:,0:6].values
y=car.iloc[:,6].values

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [ ]:
y

array([0.62765957, 0.7287234 , 0.7287234 , 0.65425532, 0.78723404,
       0.68085106, 0.79787234, 0.84574468, 0.89893617, 0.80319149,
       0.72340426, 0.7712766 , 0.86702128, 0.87234043, 0.90425532,
       0.92553191, 0.99468085, 0.9787234 , 0.00531915, 0.05851064,
       0.09042553, 0.03723404, 0.06914894, 0.2606383 , 0.05319149,
       0.10638298, 0.21808511, 0.33510638, 0.35638298, 0.60638298,
       0.07446809, 0.13297872, 0.02659574, 0.08510638, 0.17021277,
       0.18085106, 0.18085106, 0.25      , 0.37234043, 0.34574468,
       0.47340426, 0.60106383, 0.4787234 , 0.11702128, 0.35106383,
       0.35106383, 0.5106383 , 0.94148936, 0.96808511, 0.97340426,
       0.0106383 , 0.04255319, 0.12234043, 0.11170213, 0.19680851,
       0.50531915, 0.55319149, 0.63829787, 0.69680851, 0.34574468,
       0.32446809, 0.48404255, 0.46808511, 0.49468085, 0.5212766 ,
       0.81914894, 0.82446809, 0.90957447, 0.92021277, 0.91489362,
       0.93617021, 0.95744681, 0.96276596, 0.9893617 , 1.     

In [ ]:
x_train.shape

(153, 6)

In [ ]:
x_test.shape

(52, 6)

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
predict=model.predict(x_test)

In [ ]:
predict

array([0.62524895, 0.57924687, 0.79039361, 0.15391838, 0.8859149 ,
       0.23386604, 0.57924687, 0.53974896, 0.62573607, 0.4116807 ,
       0.94593739, 0.62622318, 0.38894732, 0.46810868, 0.11787186,
       0.88640202, 0.6191706 , 0.11982032, 0.47772505, 0.64780874,
       0.79077907, 0.317832  , 0.12230672, 0.86264994, 0.47095626,
       0.55112452, 0.23003967, 0.60168528, 0.39187001, 0.20128015,
       0.14127524, 0.23569004, 0.40783217, 0.14103035, 0.03278749,
       0.12620364, 0.99341487, 0.7863394 , 0.32437548, 0.05177668,
       0.53987004, 0.27275546, 0.27129411, 0.05031533, 0.71925388,
       0.19538394, 0.51773904, 0.71790786, 0.54623961, 0.89036468,
       0.32593605, 0.6267103 ])

In [ ]:
from sklearn.metrics import mean_absolute_error,r2_score,mean_squared_error

In [ ]:
mean_absolute_error(predict,y_test)

0.10310737621190205

In [ ]:
mean_squared_error(predict,y_test)

0.016289008896237862

In [ ]:
r2_score(predict,y_test)

0.7676772455886729

In [ ]:
from sklearn.metrics import accuracy_score


In [ ]:
y_test=y_test.astype("int")

In [ ]:
predict=predict.astype("int")

In [ ]:
accuracy = accuracy_score(y_test,predict)
accuracy

1.0

In [ ]:
print(accuracy*100)

100.0
