In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [ ]:
df=pd.read_csv("/content/drive/MyDrive/datasets/Advertising.csv")
df

Unnamed: 0     TV  Radio  Newspaper  Sales
0             1  230.1   37.8       69.2   22.1
1             2   44.5   39.3       45.1   10.4
2             3   17.2   45.9       69.3    9.3
3             4  151.5   41.3       58.5   18.5
4             5  180.8   10.8       58.4   12.9
..          ...    ...    ...        ...    ...
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

[200 rows x 5 columns]

In [ ]:
df.tail()

Unnamed: 0     TV  Radio  Newspaper  Sales
195         196   38.2    3.7       13.8    7.6
196         197   94.2    4.9        8.1    9.7
197         198  177.0    9.3        6.4   12.8
198         199  283.6   42.0       66.2   25.5
199         200  232.1    8.6        8.7   13.4

In [ ]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [ ]:
df.describe()

Unnamed: 0          TV       Radio   Newspaper       Sales
count  200.000000  200.000000  200.000000  200.000000  200.000000
mean   100.500000  147.042500   23.264000   30.554000   14.022500
std     57.879185   85.854236   14.846809   21.778621    5.217457
min      1.000000    0.700000    0.000000    0.300000    1.600000
25%     50.750000   74.375000    9.975000   12.750000   10.375000
50%    100.500000  149.750000   22.900000   25.750000   12.900000
75%    150.250000  218.825000   36.525000   45.100000   17.400000
max    200.000000  296.400000   49.600000  114.000000   27.000000

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  200 non-null    int64  
 1   TV          200 non-null    float64
 2   Radio       200 non-null    float64
 3   Newspaper   200 non-null    float64
 4   Sales       200 non-null    float64
dtypes: float64(4), int64(1)
memory usage: 7.9 KB


In [ ]:
df.isnull().sum()

Unnamed: 0    0
TV            0
Radio         0
Newspaper     0
Sales         0
dtype: int64

In [ ]:
df=df.drop(columns=['Unnamed: 0'],axis=1)

In [ ]:
df

TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [ ]:
df.corr()

TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.782224
Radio      0.054809  1.000000   0.354104  0.576223
Newspaper  0.056648  0.354104   1.000000  0.228299
Sales      0.782224  0.576223   0.228299  1.000000

In [ ]:
from sklearn.preprocessing import MinMaxScaler
le=MinMaxScaler()
df['TV']=le.fit_transform(df[['TV']])
df['Newspaper']=le.fit_transform(df[['Newspaper']])
df['Radio']=le.fit_transform(df[['Radio']])
df['Sales']=le.fit_transform(df[['Sales']])

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x = df.iloc[:,0:3].values
y = df.iloc[:,3].values

In [ ]:
print(x)

[[0.77578627 0.76209677 0.60598065]
 [0.1481231  0.79233871 0.39401935]
 [0.0557998  0.92540323 0.60686016]
 [0.50997633 0.83266129 0.51187335]
 [0.60906324 0.21774194 0.51099384]
 [0.02705445 0.9858871  0.65699208]
 [0.19208657 0.66129032 0.20404573]
 [0.4041258  0.39516129 0.09938434]
 [0.02671627 0.04233871 0.00615655]
 [0.67331755 0.05241935 0.18381706]
 [0.2211701  0.11693548 0.21020229]
 [0.72370646 0.48387097 0.03254178]
 [0.07811972 0.70766129 0.5769569 ]
 [0.32735881 0.15322581 0.06068602]
 [0.68785932 0.66330645 0.40193492]
 [0.65843761 0.96169355 0.46262093]
 [0.22691917 0.73790323 1.        ]
 [0.94927291 0.7983871  0.48812665]
 [0.2316537  0.41330645 0.15831135]
 [0.49577274 0.48185484 0.16534741]
 [0.73621914 0.55846774 0.46701847]
 [0.80047345 0.10282258 0.20404573]
 [0.04227257 0.32056452 0.43359719]
 [0.76969902 0.34072581 0.22779244]
 [0.20831924 0.25403226 0.15831135]
 [0.8867095  0.07056452 0.16886544]
 [0.4808928  0.59072581 0.10817942]
 [0.80960433 0.33669355 0.19

In [ ]:
print(y)

[0.80708661 0.34645669 0.30314961 0.66535433 0.44488189 0.22047244
 0.4015748  0.45669291 0.12598425 0.35433071 0.27559055 0.62204724
 0.2992126  0.31889764 0.68503937 0.81889764 0.42913386 0.8976378
 0.38188976 0.51181102 0.64566929 0.42913386 0.15748031 0.54724409
 0.31889764 0.40944882 0.52755906 0.56299213 0.68110236 0.3503937
 0.77952756 0.40551181 0.31496063 0.62204724 0.31102362 0.44094488
 0.93700787 0.51574803 0.33464567 0.78346457 0.59055118 0.61023622
 0.7519685  0.44488189 0.27165354 0.52362205 0.35433071 0.8503937
 0.51968504 0.31889764 0.38582677 0.35826772 0.82677165 0.77165354
 0.73228346 0.87007874 0.15354331 0.45669291 0.87401575 0.66141732
 0.25590551 0.88976378 0.55511811 0.48818898 0.64566929 0.30314961
 0.31102362 0.46456693 0.68110236 0.81496063 0.65748031 0.42519685
 0.28346457 0.37007874 0.60629921 0.27952756 0.20866142 0.49606299
 0.14566929 0.37007874 0.4015748  0.42125984 0.38188976 0.47244094
 0.79133858 0.53543307 0.40944882 0.56692913 0.44488189 0.5944881

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [ ]:
x_train

array([[0.96482922, 0.28024194, 0.02990325],
       [0.46398377, 0.93548387, 0.51627089],
       [0.94690565, 0.28024194, 0.32277924],
       [0.72607372, 0.47580645, 0.50395778],
       [0.97024011, 0.86693548, 0.62884785],
       [0.74974636, 0.06854839, 0.11257696],
       [0.99053094, 0.55846774, 0.01319261],
       [0.09435238, 0.03024194, 0.28759894],
       [0.14879946, 0.52016129, 0.17854002],
       [0.52722354, 0.05241935, 0.0703606 ],
       [0.67331755, 0.05241935, 0.18381706],
       [0.12681772, 0.07459677, 0.11873351],
       [0.5539398 , 0.42137097, 0.41424802],
       [0.550558  , 0.74193548, 0.06244503],
       [0.19918837, 0.24193548, 0.3764292 ],
       [0.74264457, 0.98790323, 0.02550572],
       [0.02401082, 0.78427419, 0.44239226],
       [0.25566452, 0.55443548, 0.13808267],
       [0.18769023, 0.11491935, 0.2585752 ],
       [0.58978695, 0.45362903, 0.27440633],
       [0.95908015, 0.21370968, 0.05364996],
       [0.56712885, 0.14314516, 0.10993843],
       [0.

In [ ]:
x_test

array([[0.10415962, 0.49596774, 0.01671064],
       [0.62292864, 0.4233871 , 0.19085312],
       [0.59621238, 0.1875    , 0.05364996],
       [0.64389584, 0.57862903, 0.15743184],
       [0.0906324 , 0.03225806, 0.17941953],
       [0.2962462 , 0.5141129 , 0.64291996],
       [0.4721001 , 0.03830645, 0.07651715],
       [0.75515725, 0.0483871 , 0.13456464],
       [0.06121069, 0.4375    , 0.44063325],
       [0.14305039, 0.52217742, 0.17766051],
       [0.07811972, 0.70766129, 0.5769569 ],
       [0.63307406, 0.34677419, 0.15479332],
       [0.39398039, 0.29637097, 0.04485488],
       [0.19208657, 0.66129032, 0.20404573],
       [0.68244843, 0.44959677, 0.27528584],
       [0.71931011, 0.49596774, 0.11257696],
       [0.26208996, 0.94354839, 0.30079156],
       [0.69090294, 0.90927419, 0.16974494],
       [0.2874535 , 0.72177419, 0.43095866],
       [0.40514034, 0.57459677, 0.12225154],
       [0.67095029, 0.61693548, 0.33773087],
       [0.32127156, 0.02822581, 0.06244503],
       [0.

In [ ]:
y_train

array([0.56299213, 0.69291339, 0.57086614, 0.61023622, 0.96850394,
       0.38976378, 0.7519685 , 0.22440945, 0.33464567, 0.3503937 ,
       0.35433071, 0.23622047, 0.50787402, 0.64566929, 0.31889764,
       0.90944882, 0.19685039, 0.40944882, 0.27952756, 0.52362205,
       0.52755906, 0.3976378 , 0.42519685, 0.31889764, 0.36220472,
       0.34645669, 0.22047244, 0.42913386, 0.12598425, 0.39370079,
       0.7007874 , 0.15354331, 0.27952756, 0.37007874, 0.43307087,
       0.4015748 , 0.22440945, 0.53543307, 0.87401575, 0.40551181,
       0.31102362, 0.34251969, 0.36614173, 0.71653543, 0.30314961,
       0.61417323, 0.69291339, 0.51181102, 0.23622047, 0.52755906,
       0.56692913, 0.8976378 , 0.44094488, 0.93700787, 0.16141732,
       0.47244094, 0.73228346, 0.48818898, 0.39370079, 0.22047244,
       0.93700787, 0.61811024, 0.70866142, 0.53937008, 0.87007874,
       0.44488189, 0.38188976, 0.54724409, 0.51574803, 0.37007874,
       0.49212598, 0.77952756, 0.45669291, 0.64566929, 0.82677

In [ ]:
y_test

array([0.31102362, 0.54724409, 0.44094488, 0.61811024, 0.20866142,
       0.44488189, 0.34251969, 0.39370079, 0.21259843, 0.31496063,
       0.2992126 , 0.51574803, 0.40551181, 0.4015748 , 0.59055118,
       0.60629921, 0.51181102, 0.82677165, 0.46062992, 0.49606299,
       0.65748031, 0.31102362, 0.50393701, 0.26771654, 0.66535433,
       0.73228346, 0.33464567, 0.38976378, 0.81102362, 0.81889764,
       0.19685039, 0.31889764, 0.62992126, 0.40944882, 0.25590551,
       0.7519685 , 0.81496063, 0.31496063, 0.80708661, 0.46456693,
       0.6023622 , 0.72834646, 0.41732283, 0.06299213, 0.79133858,
       0.36220472, 0.27165354, 0.62204724, 0.52362205, 0.56299213])

In [ ]:
x_train.shape

(150, 3)

In [ ]:
x_test.shape

(50, 3)

In [ ]:
y_train.shape

(150,)

In [ ]:
y_test.shape

(50,)

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
model=LinearRegression()


In [ ]:
model.fit(x_train,y_train)

LinearRegression()

In [ ]:
predict=model.predict(x_test)

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

In [ ]:
predict=predict.astype("int")
y_test=y_test.astype("int")

In [ ]:
print(mean_squared_error(y_test,predict))

0.0


In [ ]:
print(confusion_matrix(predict,y_test))

[[50]]


In [ ]:
print(classification_report(predict,y_test))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        50

    accuracy                           1.00        50
   macro avg       1.00      1.00      1.00        50
weighted avg       1.00      1.00      1.00        50



In [ ]:
accuracy = accuracy_score(predict,y_test)
accuracy

1.0

In [ ]:
print(accuracy*100)

100.0
